backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "images/upload" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Header Content", name: "header_content", widget: "markdown", required: false}
      - {label: "Select strip title", name: "select_strip_title", widget: "string", required: false}
      - label: "Select Strip Objects"
        name: "select_strip_objects"
        widget: "list"
        required: false
        fields:
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Link", name: "link", widget: "string"}