backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "images/upload" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Reference", name: "reference", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Header Content", name: "header_content", widget: "markdown", required: false}
      - {label: "Header Icons", name: "header_icons", widget: "string", required: false}
      - {label: "Select strip title", name: "select_strip_title", widget: "string", required: false}
      - label: "Select Strip Objects"
        name: "select_strip_objects"
        widget: "list"
        required: false
        fields:
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Link", name: "link", widget: "string"}
      - {label: "Strip 1 Content", name: "strip_1_content", widget: "markdown", required: false}
      - {label: "Strip 2 Content", name: "strip_2_content", widget: "markdown", required: false}
  - name: "config"
    label: "Config"
    preview: false
    files:
      - label: "Footer navigation"
        name: "navigation"
        file: "_data/footer_navigation.yml"
        fields:
          - label: "Footer Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Is header?, name: header, widget: boolean}
      - label: "Reviews"
        name: "reviews"
        file: "_data/reviews.yml"
        fields:
          - label: "Reviews"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: image, widget: image}
              - {label: Category, name: category, widget: string}
      - label: "FAQs"
        name: "faqs"
        file: "_data/faqs.yml"
        fields:
          - label: "FAQs"
            name: "items"
            widget: "list"
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}
              - {label: Category, name: category, widget: string}
      - label: "Forms"
        name: "forms"
        file: "_data/forms.yml"
        fields:
          - label: "Forms"
            name: "items"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Submit text, name: submit_text, widget: string}
              - {label: Category, name: category, widget: string}
              - {label: Pre text, name: pre_text, widget: markdown}
              - label: Fields
                name: form_fields
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Helptext, name: helptext, widget: string}
                  - {label: Type, name: type, widget: string}
                  - {label: Placeholder, name: placeholder, widget: string}
                  - label: Options
                    name: options
                    widget: list
                    fields:
                      - {label: Name, name: name, widget: string}
                  - {label: Required?, name: required, widget: boolean}